### ISSUE TITLE
[Enquiry] How accurate is the output 

### ISSUE THREAD

**Issue by mohamedsayed18** [ziggyjosh16/app-fall-detector#1]
I'm here from your StackOverflow post. it was really helpful
I applied the same method but the highest confidence I get at any Keypoint is 0.009. so my points are scattered randomly. I tried on different images (including an image from mscoco) but it didn't work.
here is my [notebook](https://colab.research.google.com/drive/17Qc-nP8vWuAmIQvlwCHbsd1QinRJyDh6).
another question why in offsets[y,x,k], we use y then x not the opposite

**Comment by ziggyjosh16** [comment]
The `point()` method returns a y then an x in that order. Try switching x and y when you unpack the point coordinates.

```
# Draw points on the image 
draw_on = cv2.resize(img, (257,257))
for i in keypoints:
  x, y = i.point() #switch x and y
  cv2.circle(draw_on, (y,x), 2, (255,0,0), -1)

plt.imshow(draw_on)
```

**Comment by mohamedsayed18** [comment]
thanks for your help
I still get negative values in the coordinates of the points. I didn't figure it yet 
I have a question how accurate is the model?  does it get the joints correctly

**Comment by ziggyjosh16** [comment]
From testing the pretrained model on images scraped from Google. I have noted the accuracy to be okay. The model is not the best at detecting the eyes and the nose.

**Comment by ziggyjosh16** [comment]
You should be able to get acceptable accuracy training your own model.

**Comment by mohamedsayed18** [comment]
thank you maybe I am doing parsing the output in a wrong way
